
CREATE TABLE MOVIE_REVIEW
(
  MOVIES_UNIQUE_ID  VARCHAR(200) NOT NULL COMMENT '영화 UID',
  REVIEWS_UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '리뷰 UID'
);

CREATE TABLE MOVIES
(
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '유니크 아이디',
  TITLE     VARCHAR(200) NOT NULL COMMENT '영화 제목',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '영화';

CREATE TABLE REVIEWS
(
  UNIQUE_ID    VARCHAR(200) NOT NULL COMMENT '유니크 아이디',
  TITLE        VARCHAR(200) NOT NULL COMMENT '리뷰 제목',
  COMMENT      VARCHAR(200) NULL     COMMENT '리뷰 내용',
  CREATED_DATE TIMESTAMP    NOT NULL COMMENT '리뷰 작성일',
  STAR_POINT   DECIMAL      NULL     COMMENT '별점',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '리뷰';

CREATE TABLE USER_REVIEW
(
  USERS_UNIQUE_ID   VARCHAR(200) NOT NULL COMMENT '사용자 UID',
  REVIEWS_UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '리뷰 UID'
);

CREATE TABLE USERS
(
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '유니크 아이디',
  NAME      VARCHAR(200) NOT NULL COMMENT '사용자 이름',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '사용자';

ALTER TABLE USER_REVIEW
  ADD CONSTRAINT FK_USERS_TO_USER_REVIEW
    FOREIGN KEY (USERS_UNIQUE_ID)
    REFERENCES USERS (UNIQUE_ID);

ALTER TABLE USER_REVIEW
  ADD CONSTRAINT FK_REVIEWS_TO_USER_REVIEW
    FOREIGN KEY (REVIEWS_UNIQUE_ID)
    REFERENCES REVIEWS (UNIQUE_ID);

ALTER TABLE MOVIE_REVIEW
  ADD CONSTRAINT FK_MOVIES_TO_MOVIE_REVIEW
    FOREIGN KEY (MOVIES_UNIQUE_ID)
    REFERENCES MOVIES (UNIQUE_ID);

ALTER TABLE MOVIE_REVIEW
  ADD CONSTRAINT FK_REVIEWS_TO_MOVIE_REVIEW
    FOREIGN KEY (REVIEWS_UNIQUE_ID)
    REFERENCES REVIEWS (UNIQUE_ID);
